SELECT
    p.PRODUCT_CODE,
    SUM(os.SALES_AMOUNT * p.PRICE) AS SALES
FROM
    OFFLINE_SALE os
    INNER JOIN PRODUCT p ON os.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    product_code
ORDER BY
    SALES DESC,
    PRODUCT_CODE ASC;