SELECT
    b.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(b.PRICE * SALES) AS TOTAL_SALES
FROM
    BOOK b
    INNER JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID
    INNER JOIN BOOK_SALES s ON b.BOOK_ID = s.BOOK_ID
WHERE
    DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY
    b.AUTHOR_ID,
    b.CATEGORY
ORDER BY
    b.AUTHOR_ID,
    b.CATEGORY DESC